{{- include "k8s-runner.configureCatalog" . -}}
{{- $rbac := "" -}}
{{- if .Values.rbac.clusterWide -}}
  {{- $rbac = include "service-base.rbac" . -}}
{{- end -}}
{{- $sa := include "service-base.serviceAccount" . -}}
{{- $svc := include "service-base.service" . -}}
{{- $deploy := include "service-base.deployment" . -}}
{{- $hpa := include "service-base.hpa" . -}}
{{- $ingress := include "service-base.ingress" . -}}
{{- $pdb := include "service-base.pdb" . -}}
{{- $metrics := include "service-base.metrics" . -}}
{{- $parts := list -}}
{{- range (list $rbac $sa $svc $deploy $hpa $ingress $pdb $metrics) -}}
  {{- if . -}}
    {{- $parts = append $parts . -}}
  {{- end -}}
{{- end -}}
{{ join "\n---\n" $parts }}
